### PR TITLE
use bash rather than sh

### PR DESCRIPTION
**Pull request by jjmcdn**
In systems with /bin/sh linked to a POSIX-strict shell implementation, the check at the start of `switch_priority()` will fail with an error like `Syntax error: "(" unexpected`.  The way `pairs` is used later on in the script makes it clear the assignment is intended to be done as an array, which is the expected behaviour with `var=(_foo_)` in bash. Switching to invoking `bash` directly seems to be the appropriate resolution.

### CODE REVIEW

**Comment by vaygr** [comment]
Thank you for flagging this!

I believe this was missed in `switch_priority()` since it's rather new addition. If this is the only place, I'd prefer to keep the code as close to POSIX-compliant as possible and rather reimplement `switch_priority()`.

I can probably look into this unless you want to give it a shot?

**Comment by jjmcdn** [comment]
> Thank you for flagging this!
> 
> I believe this was missed in `switch_priority()` since it's rather new addition. If this is the only place, I'd prefer to keep the code as close to POSIX-compliant as possible and rather reimplement `switch_priority()`.

I did a quick scan of the code and I don't see anywhere else that looks like it's using the bash array behaviour, so it's probably safe to assume it's just this one spot.

> I can probably look into this unless you want to give it a shot?

If you have a bit of time now go for it. I'll have time in a few days but I would want to test it with a bunch of different inputs since this short-cut with arrays helps avoid some potential headaches with the crazy names people give their APs.  :smiley:

**Comment by vaygr** [comment]
@jjmcdn Should be fixed by 2071a72.

Could you please try the latest master and see if that's resolved?

**Comment by jjmcdn** [comment]
> @jjmcdn Should be fixed by [2071a72](https://github.com/sourcemage/rofi-connman/commit/2071a72495368aafe4ff36cd7284463d78a1d58c).
> 
> Could you please try the latest master and see if that's resolved?

That certainly helped, but it turns out there were other bits that weren't strictly POSIX.  I'm closing this PR since it's clear this is a solvable problem and you don't have to switch to bash, but I'm opening https://github.com/sourcemage/rofi-connman/pull/3 instead where I clean up (I think) all the other items.  I'd test that carefully, though, since it's not a complicated set of changes but it did touch more of the script than I'd originally intended.  :smile:

**Pull request closed without merging**
